version: '3.7'
services:
        pg:
                image: postgres
                ports:
                        - "5432:5432"
                volumes:
                        - ./pg:/docker-entrypoint-initdb.d/
                environment:
                        - "POSTGRES_USER=issue_test"
                        - "POSTGRES_PASSWORD=issue_test"
                        - "POSTGRES_DB=issue_tracker"
