version: '3.7'
services:
        frontend:
                build: ./frontend
                container_name: frontend
                ports:
                        - "8080:8080"
                networks:
                        - app-network
                depends_on:
                        - backend
        backend:
                build: ./backend
                ports:
                        - "3000:3000"
                networks:
                        - app-network
                depends_on:
                        - db 
        db:
                image: postgres
                ports:
                        - "5432:5432"
                volumes:
                        - ./pg:/docker-entrypoint-initdb.d/
                environment:
                        - "POSTGRES_USER=issue_test"
                        - "POSTGRES_PASSWORD=issue_test"
                        - "POSTGRES_DB=issue_tracker"
                networks:
                        - app-network

networks:
        app-network:
                driver: bridge
